import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, Download, FileText, FolderOpen as FilesIcon, GitBranch, X } from "lucide-react";
import { CopyButton } from "@/components/chat-code";
import { Button } from "@/components/ui/button";
import { loadAllFiles, normalizePath, type SavedFile } from "@/lib/chat-store";
import { useChatStore } from "@/lib/use-chat-store";
export const Route = createFileRoute("/chat/$sessionId/files")({ head: () => ({ meta: [
  { title: "File Manager — WenGPT" }, { name: "description", content: "File yang dibuat WenGPT di semua sesi." }, { property: "og:title", content: "File Manager — WenGPT" }, { property: "og:description", content: "File yang dibuat WenGPT di semua sesi." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" },
] }), component: FilesPage });
const name = (path: string) => path.split("/").pop() || path;
function download(file: SavedFile) { const url = URL.createObjectURL(new Blob([file.content], { type: "text/plain;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name(file.path); anchor.click(); URL.revokeObjectURL(url); }
function FilesPage() { const { sessionId } = Route.useParams(); useChatStore(); const files = loadAllFiles(); const [open, setOpen] = useState<string | null>(null); useEffect(() => { const hash = decodeURIComponent(window.location.hash.slice(1)); if (hash) setOpen(normalizePath(hash)); }, []); const active = files.find((file) => file.path === open); return <main className="h-dvh overflow-y-auto bg-background text-foreground"><header className="sticky top-0 z-20 grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-border/60 bg-background/88 px-4 py-3 backdrop-blur-xl"><Button asChild variant="outline" size="icon"><Link to="/chat/$sessionId" params={{ sessionId }}><ArrowLeft className="size-4" /></Link></Button><div className="min-w-0"><div className="flex items-center gap-2"><FilesIcon className="size-4 text-primary" /><h1 className="text-sm font-semibold">File Manager</h1></div><p className="text-[11px] text-muted-foreground">{files.length} file · dipakai di semua sesi</p></div><Button asChild variant="outline" size="icon"><Link to="/chat/$sessionId/timeline" params={{ sessionId }}><GitBranch className="size-4" /></Link></Button></header><section className="mx-auto max-w-3xl px-4 py-5">{files.length === 0 ? <p className="py-20 text-center text-sm text-muted-foreground">Belum ada file.</p> : <ul className="overflow-hidden rounded-lg border border-border/70 bg-card/55">{files.map((file) => <li key={file.path} className="border-b border-border/50 last:border-0"><button type="button" onClick={() => setOpen(file.path)} className="flex w-full min-w-0 items-center gap-3 px-3 py-3 text-left active:bg-muted"><span className="grid size-9 shrink-0 place-items-center rounded-md bg-muted"><FileText className="size-4 text-primary" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{name(file.path)}</span><span className="block truncate font-mono text-[11px] text-muted-foreground">{file.path.replace(/^\/home\/user\//, "")} · {file.sessionTitle ?? ""}</span></span></button></li>)}</ul>}</section>{active && <div className="fixed inset-0 z-40 flex flex-col bg-background/96 backdrop-blur-xl"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2 border-b border-border/60 px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{name(active.path)}</p><p className="truncate font-mono text-[11px] text-muted-foreground">{active.path}</p></div><div className="flex"><CopyButton text={active.content} /><Button variant="ghost" size="icon" onClick={() => download(active)}><Download className="size-4" /></Button><Button variant="ghost" size="icon" onClick={() => { setOpen(null); history.replaceState(null, "", `/chat/${sessionId}/files`); }}><X className="size-4" /></Button></div></div><pre className="min-h-0 flex-1 overflow-auto px-4 py-3 font-mono text-xs leading-5 whitespace-pre-wrap break-words">{active.content || "(file kosong)"}</pre></div>}</main>; }
