/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTerminalRouteImport } from './routes/api/terminal'
import { Route as ChatSessionIdRouteImport } from './routes/chat.$sessionId'
import { Route as ChatSessionIdIndexRouteImport } from './routes/chat.$sessionId.index'
import { Route as ChatSessionIdFilesRouteImport } from './routes/chat.$sessionId.files'
import { Route as ChatSessionIdTerminalRouteImport } from './routes/chat.$sessionId.terminal'
import { Route as ChatSessionIdTimelineRouteImport } from './routes/chat.$sessionId.timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalRoute = ApiTerminalRouteImport.update({
  id: '/api/terminal',
  path: '/api/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdIndexRoute = ChatSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatSessionIdRoute,
} as any)
const ChatSessionIdFilesRoute = ChatSessionIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ChatSessionIdRoute,
} as any)
const ChatSessionIdTerminalRoute = ChatSessionIdTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => ChatSessionIdRoute,
} as any)
const ChatSessionIdTimelineRoute = ChatSessionIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ChatSessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/terminal': typeof ApiTerminalRoute
  '/chat/$sessionId': typeof ChatSessionIdRouteWithChildren
  '/chat/$sessionId/files': typeof ChatSessionIdFilesRoute
  '/chat/$sessionId/terminal': typeof ChatSessionIdTerminalRoute
  '/chat/$sessionId/timeline': typeof ChatSessionIdTimelineRoute
  '/chat/$sessionId/': typeof ChatSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/terminal': typeof ApiTerminalRoute
  '/chat/$sessionId/files': typeof ChatSessionIdFilesRoute
  '/chat/$sessionId/terminal': typeof ChatSessionIdTerminalRoute
  '/chat/$sessionId/timeline': typeof ChatSessionIdTimelineRoute
  '/chat/$sessionId': typeof ChatSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/terminal': typeof ApiTerminalRoute
  '/chat/$sessionId': typeof ChatSessionIdRouteWithChildren
  '/chat/$sessionId/files': typeof ChatSessionIdFilesRoute
  '/chat/$sessionId/terminal': typeof ChatSessionIdTerminalRoute
  '/chat/$sessionId/timeline': typeof ChatSessionIdTimelineRoute
  '/chat/$sessionId/': typeof ChatSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/api/chat'
    | '/api/terminal'
    | '/chat/$sessionId'
    | '/chat/$sessionId/files'
    | '/chat/$sessionId/terminal'
    | '/chat/$sessionId/timeline'
    | '/chat/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/api/chat'
    | '/api/terminal'
    | '/chat/$sessionId/files'
    | '/chat/$sessionId/terminal'
    | '/chat/$sessionId/timeline'
    | '/chat/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/api/chat'
    | '/api/terminal'
    | '/chat/$sessionId'
    | '/chat/$sessionId/files'
    | '/chat/$sessionId/terminal'
    | '/chat/$sessionId/timeline'
    | '/chat/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTerminalRoute: typeof ApiTerminalRoute
  ChatSessionIdRoute: typeof ChatSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal': {
      id: '/api/terminal'
      path: '/api/terminal'
      fullPath: '/api/terminal'
      preLoaderRoute: typeof ApiTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId/': {
      id: '/chat/$sessionId/'
      path: '/'
      fullPath: '/chat/$sessionId/'
      preLoaderRoute: typeof ChatSessionIdIndexRouteImport
      parentRoute: typeof ChatSessionIdRoute
    }
    '/chat/$sessionId/files': {
      id: '/chat/$sessionId/files'
      path: '/files'
      fullPath: '/chat/$sessionId/files'
      preLoaderRoute: typeof ChatSessionIdFilesRouteImport
      parentRoute: typeof ChatSessionIdRoute
    }
    '/chat/$sessionId/terminal': {
      id: '/chat/$sessionId/terminal'
      path: '/terminal'
      fullPath: '/chat/$sessionId/terminal'
      preLoaderRoute: typeof ChatSessionIdTerminalRouteImport
      parentRoute: typeof ChatSessionIdRoute
    }
    '/chat/$sessionId/timeline': {
      id: '/chat/$sessionId/timeline'
      path: '/timeline'
      fullPath: '/chat/$sessionId/timeline'
      preLoaderRoute: typeof ChatSessionIdTimelineRouteImport
      parentRoute: typeof ChatSessionIdRoute
    }
  }
}

interface ChatSessionIdRouteChildren {
  ChatSessionIdFilesRoute: typeof ChatSessionIdFilesRoute
  ChatSessionIdTerminalRoute: typeof ChatSessionIdTerminalRoute
  ChatSessionIdTimelineRoute: typeof ChatSessionIdTimelineRoute
  ChatSessionIdIndexRoute: typeof ChatSessionIdIndexRoute
}

const ChatSessionIdRouteChildren: ChatSessionIdRouteChildren = {
  ChatSessionIdFilesRoute: ChatSessionIdFilesRoute,
  ChatSessionIdTerminalRoute: ChatSessionIdTerminalRoute,
  ChatSessionIdTimelineRoute: ChatSessionIdTimelineRoute,
  ChatSessionIdIndexRoute: ChatSessionIdIndexRoute,
}

const ChatSessionIdRouteWithChildren = ChatSessionIdRoute._addFileChildren(
  ChatSessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTerminalRoute: ApiTerminalRoute,
  ChatSessionIdRoute: ChatSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
